matches:
  - trigger: ":block:"
    label: "Markdown - Code block"
    replace: |-
        ```$|$
        ```
    force_clipboard: true

  - trigger: ":code:"
    label: "Markdown - Inline code"
    replace: |-
        `$|$`
    force_clipboard: true

  - trigger: ":h1:"
    label: "Markdown - Header1"
    replace: "#"

  - trigger: ":h2:"
    label: "Markdown - Header2"
    replace: "##"

  - trigger: ":h3:"
    label: "Markdown - Header3"
    replace: "###"

  - trigger: ":h4:"
    label: "Markdown - Header4"
    replace: "####"

  - trigger: ":h5:"
    label: "Markdown - Header5"
    replace: "#####"

  - trigger: ":h6:"
    label: "Markdown - Header6"
    replace: "######"

  - trigger: ":bold:"
    label: "Markdown - Bold"
    replace: "**$|$**"

  - trigger: ":italic:"
    label: "Markdown - Italic"
    replace: "*$|$*"

  - trigger: ":strike:"
    label: "Markdown - Strikethrough"
    replace: "~~$|$~~"

  - trigger: ":url:"
    label: "Markdown - URL"
    replace: "[$|$]()"

  - trigger: ":img:"
    label: "Markdown - Image"
    replace: "![]($|$)"

  - trigger: ":horizontal:"
    label: "Markdown - Horizontal line"
    replace: "___"

  - trigger: ":task:"
    label: "Markdown - Task"
    replace: "- [ ] "

  - trigger: ":taskdone:"
    label: "Markdown - Task completed"
    replace: "- [x] "

  - trigger: ":collapse:"
    label: "Markdown - Collapse block"
    replace: |-
        <details>
        <summary></summary>
        $|$
        </details>
    force_clipboard: true

  - trigger: ":comment:"
    label: "Markdown - Comment"
    replace: "<!--- $|$ -->"
    force_clipboard: true

  - trigger: ":mdt2:"
    label: "Markdown - Two Column Table"
    replace: |-
        |  $|$  |    |
        |:--:|:--:|
        |    |    |

    force_clipboard: true


  - trigger: ":mdt3:"
    label: "Markdown - Three Column Table"
    replace: |-
        |  $|$  |    |    |
        |:--:|:--:|:--:|
        |    |    |    |
    force_clipboard: true


  - trigger: ":mdt4:"
    label: "Markdown - Four Column Table"
    replace: |-
        |  $|$  |    |    |    |
        |:--:|:--:|:--:|:--:|
        |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt5:"
    label: "Markdown - Five Column Table"
    replace: |-
        |  $|$  |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt6:"
    label: "Markdown - Six Column Table"
    replace: |-
        |  $|$  |    |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt7:"
    label: "Markdown - Seven Column Table"
    replace: |-
        |  $|$  |    |    |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt8:"
    label: "Markdown - Eight Column Table"
    replace: |-
        |  $|$  |    |    |    |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt9:"
    label: "Markdown - Nine Column Table"
    replace: |-
        |  $|$  |    |    |    |    |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdt10:"
    label: "Markdown - Ten Column Table"
    replace: |-
        |  $|$  |    |    |    |    |    |    |    |    |    |
        |:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
        |    |    |    |    |    |    |    |    |    |    |
    force_clipboard: true


  - trigger: ":mdr2:"
    label: "Markdown - Two Column Row"
    replace: "|  $|$  |    |"
    force_clipboard: true


  - trigger: ":mdr3:"
    label: "Markdown - Three Column Row"
    replace: "|  $|$  |    |    |"
    force_clipboard: true


  - trigger: ":mdr4:"
    label: "Markdown - Four Column Row"
    replace: "|  $|$  |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr5:"
    label: "Markdown - Five Column Row"
    replace: "|  $|$  |    |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr6:"
    label: "Markdown - Six Column Row"
    replace: "|  $|$  |    |    |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr7:"
    label: "Markdown - Seven Column Row"
    replace: "|  $|$  |    |    |    |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr8:"
    label: "Markdown - Eight Column Row"
    replace: "|  $|$  |    |    |    |    |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr9:"
    label: "Markdown - Nine Column Row"
    replace: "|  $|$  |    |    |    |    |    |    |    |    |"
    force_clipboard: true


  - trigger: ":mdr10:"
    label: "Markdown - Ten Column Row"
    replace: "|  $|$  |    |    |    |    |    |    |    |    |    |"
    force_clipboard: true


